name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:

          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.100.1/hugo_0.100.1_Linux-64bit.deb &&sudo apt install hugo_0.100.1_Linux-64bit.deb 

      


      - name: Build
        run: hugo --minify
        
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: public/  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        with:
          personal_token: ${{ secrets.GH_TOKEN }}
